name: self ci checks

on:
  push:
    branches:
      - kathur_dev

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 150

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: test output
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
